sudo: required
branches:
  only:
    - master
services:
  - docker
language: go
go:
 - "1.14.x"
env:
  global:
    - GO111MODULE=on
    - TEAMCITY_ADDR=http://localhost:8112
    - TF_ACC=1
    - TEAMCITY_USER=admin
    - TEAMCITY_PASSWORD=admin
cache:
  directories:
    - $GOPATH/pkg/mod
before_install:
  - sudo apt-get update
  - sudo apt-get -y install bsdtar
script:
  # run acceptance tests
 - ./integration_tests/start_teamcity.sh  # start and wait for TeamCity
 - go test -v -timeout 1800s ./...
