#Use to spin up teamcity container for testing
version: "3"
services:
  server:
    image: jetbrains/teamcity-server:2018.1
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
