version: "3"
services:
  server:
    image: jetbrains/teamcity-server:2019.2.2
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
